version: "3.5"

services:
  api:
    build:
      context: .
    ports:
        - "8080:80"
    env_file: ./.env
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    command: telegraf --test
    depends_on:
      - api
